### ISSUE TITLE
scroll in preview pane breaks scroll in email select pain

### ISSUE THREAD

**Issue by asullivan321** [DustinLuck/Gmail-Preview-Pane-Arrow-Scrolling-Userscript#4]
This used to work perfectly but now it only works in preview pane and it breaks the arrow scroll to select the email in the center pain. I don't know how to fix these things....

**Comment by DustinLuck** [comment]
Are you saying that at some point you were able to use this script to both scroll the email preview pane and select emails from the thread list using the arrow keys on the keyboard? If so, how was that possible when both panes are visible at the same time? How would you switch between selecting emails and scrolling the preview pane?

If I'm not understanding the issue you're facing, please provide more details on exactly how it was working before and how it is behaving now.
